import Providers from "../utils/provider"
import './global.css'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang='ko'>
      <body>
        <main className='w-desktop mx-auto bg-white min-h-full'>
        <Providers>{children}</Providers>
        </main>
      </body>
    </html>
  )
}
